### ISSUE TITLE
nullpointer when invoking createConsumer service

### ISSUE THREAD

**Issue by tanweishen** [dashingsat/ISKafkaBridge#1]
Hi, I have imported the IS package into my integration server and when I invoke the createConsumer service, I encounter the following error:

java.lang.NullPointerException at java.util.Hashtable.put(Hashtable.java:459) at com.gcs.lib.ISKafkaIntegration.WmKafkaConsumer.createConsumer(WmKafkaConsumer.java:50) at ISKafkaIntegrationModule.service.createConsumer(service.java:57) at sun.reflect.GeneratedMethodAccessor168.invoke(Unknown Source) at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) at java.lang.reflect.Method.invoke(Method.java:497) at com.wm.app.b2b.server.JavaService.baseInvoke(JavaService.java:407) at com.wm.app.b2b.server.invoke.InvokeManager.process(InvokeManager.java:643) at com.wm.app.b2b.server.util.tspace.ReservationProcessor.process(ReservationProcessor.java:39) at com.wm.app.b2b.server.invoke.StatisticsProcessor.process(StatisticsProcessor.java:49) at com.wm.app.b2b.server.invoke.ServiceCompletionImpl.process(ServiceCompletionImpl.java:243) at com.wm.app.b2b.server.invoke.ValidateProcessor.process(ValidateProcessor.java:49) at com.wm.app.b2b.server.invoke.PipelineProcessor.process(PipelineProcessor.java:171) at com.wm.app.b2b.server.ACLManager.process(ACLManager.java:303) at com.wm.app.b2b.server.invoke.DispatchProcessor.process(DispatchProcessor.java:34) at com.wm.app.b2b.server.AuditLogManager.process(AuditLogManager.java:371) at com.wm.app.b2b.server.invoke.InvokeManager.invoke(InvokeManager.java:547) at com.wm.app.b2b.server.invoke.InvokeManager.invoke(InvokeManager.java:384) at com.wm.app.b2b.server.HTTPInvokeHandler._process(HTTPInvokeHandler.java:254) at com.wm.app.b2b.server.InvokeHandler.process(InvokeHandler.java:101) at com.wm.app.b2b.server.HTTPDispatch.handleRequest(HTTPDispatch.java:178) at com.wm.app.b2b.server.Dispatch.run(Dispatch.java:386) at com.wm.util.pool.PooledThread.run(PooledThread.java:127) at java.lang.Thread.run(Thread.java:745)

**Comment by dashingsat** [comment]
I Wii look into this.. Just a question.. Did you create the producer first.. And kindly let me know the parameters through which you invoked the create consumer service

**Comment by tanweishen** [comment]
The producer is created by calling http://localhost:5555/invoke/ISKafkaIntegrationModule.service/createProducer?bootstrapServers=192.168.1.152:9092

The createConsumer service is invoke by calling http://localhost:5555/invoke/ISKafkaIntegrationModule.service/createConsumer?name=test&bootstrapServers=192.168.1.152:9092&topicName=flight&serviceName=ISKafkaIntegrationModule.test:ackService

**Comment by dashingsat** [comment]
Kindly pass the "clientGroupId " in your parameters , we will see if this can be defaulted ..

**Comment by tanweishen** [comment]
Thank you for your assistance, it is working now. On a separate note, can i know what is the data format that is accepted? I can't seem to send proper messages via the producer. All my messages are symbols. Thanks!

**Comment by dashingsat** [comment]
Glad .. it's working for you .. Currently you need to send the data in IData format .. The key should be your String data type .. and the value should be IData .. 

![ki](https://cloud.githubusercontent.com/assets/2674916/16755785/cbb5aa90-481d-11e6-8120-aff28d06baa7.png)

**Comment by dashingsat** [comment]
I have added a screenshot .. Kindly have a look

**Comment by tanweishen** [comment]
Should the value field be empty? I have tried sending out in this format but I only receive symbols instead of the original string message.

**Comment by dashingsat** [comment]
No the value should not be empty .. Can you let me know what are you receiving .. Kindly add a screenshot or so ..

**Comment by tanweishen** [comment]
I am unable to key in any value in the value fields. The following are the screenshots.

![error2](https://cloud.githubusercontent.com/assets/14120019/16756263/9fedbeca-4836-11e6-89dc-ce1c93410ce9.png)

![error](https://cloud.githubusercontent.com/assets/14120019/16756123/845636c0-4835-11e6-8fdd-4b8262465625.png)

**Comment by dashingsat** [comment]
You can key in by clicking the button on the top left side ..
![in](https://cloud.githubusercontent.com/assets/2674916/16756458/c754f4ce-4822-11e6-84f3-73ea687e5ec1.PNG)

**Comment by tanweishen** [comment]
I try sending using testing as the value and I still receive symbols. The following is the screenshot, is this normal?
![error3](https://cloud.githubusercontent.com/assets/14120019/16757003/bb5144b6-483b-11e6-8988-ccf9124c43c1.png)

**Comment by dashingsat** [comment]
I guess that is okay because , you are trying to read the message from the console consumer , which does not understand IData .. So it's bound to receive the data not in a proper format .. If you have run the create consumer service in IS itself , then the service you mentioned in the parameter there would be invoked ..

http://localhost:5555/invoke/ISKafkaIntegrationModule.service/createConsumer?name=test&bootstrapServers=192.168.1.152:9092&topicName=flight&**_serviceName=ISKafkaIntegrationModule.test:ackService_**  

I am referring to the service name section .. In the above section , ISKafkaIntegrationModule.test:ackService will get invoked , when the desired messages gets into the topic to which the subscription subscribes ..

**Comment by tanweishen** [comment]
The data I am sending is a JSON string. Will the IData format append some data to the JSON string which cause the symbols to appear? Can I send in simple string format instead of IData? Thanks!

**Comment by dashingsat** [comment]
In the current version , you can't .. But I will add a feature to support some common datatypes like Strings ..

**Comment by dashingsat** [comment]
Can I close the current issue .. We can put the support request for adding other data types in the feature request ..

**Comment by tanweishen** [comment]
Yes, the issue has been resolved. Thank You very much for your help!
